baseURL = 'https://smarthomeideas.info/'
languageCode = 'en-gb'
title = 'Smart Home Ideas'
theme = "hugo-theme-m10c"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true